## Scraping AWOIAF Character Names
Scrapes the full character list from the A Wiki of Ice and Fire and stores results in a CSV.

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

### Fetch the page

In [2]:
URL = 'https://awoiaf.westeros.org/index.php/List_of_characters'

# Full browser User-Agent required — the server returns 403 for generic bot strings
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
}
page = requests.get(URL, headers=headers)

soup = BeautifulSoup(page.content, 'html.parser')
print(f'Status code: {page.status_code}')

Status code: 200

### Extract character names
The page is a MediaWiki article. Character names are listed as `<li>` items inside the main content div (`mw-parser-output`), each wrapped in an `<a>` tag.

In [3]:
# Scope to the main article body to avoid nav/footer links
content = soup.find('div', class_='mw-parser-output')

characters = []

for li in content.find_all('li'):
    a = li.find('a')  # First <a> in each li is the character link
    if a and a.get('href', '').startswith('/index.php/'):  # Skip TOC anchor links (#A, #B ...)
        name = a.get_text(strip=True)
        link = a.get('href')
        if name:
            characters.append({'name': name, 'ID': link})

print(f'Found {len(characters)} characters')
print(characters[:10])  # Preview first 10

Found 3698 characters
[{'name': 'A certain man', 'ID': '/index.php/A_certain_man'}, {'name': 'Abelar Hightower', 'ID': '/index.php/Abelar_Hightower'}, {'name': 'Abelon', 'ID': '/index.php/Abelon'}, {'name': 'Addam of Duskendale', 'ID': '/index.php/Addam_of_Duskendale'}, {'name': 'Addam Frey', 'ID': '/index.php/Addam_Frey'}, {'name': 'Addam Hightower', 'ID': '/index.php/Addam_Hightower'}, {'name': 'Addam Marbrand', 'ID': '/index.php/Addam_Marbrand'}, {'name': 'Addam Osgrey', 'ID': '/index.php/Addam_Osgrey'}, {'name': 'Addam Rivers', 'ID': '/index.php/Addam_Rivers'}, {'name': 'Addam Velaryon', 'ID': '/index.php/Addam_Velaryon'}]

### Save to CSV

In [4]:
df = pd.DataFrame(characters)
df.to_csv('characters.csv', index=False)

print(f'Saved {len(df)} characters to characters.csv')
df.head(10)

Saved 3698 characters to characters.csv

                  name                              ID
0        A certain man        /index.php/A_certain_man
1     Abelar Hightower     /index.php/Abelar_Hightower
2               Abelon               /index.php/Abelon
3  Addam of Duskendale  /index.php/Addam_of_Duskendale
4           Addam Frey           /index.php/Addam_Frey
5      Addam Hightower      /index.php/Addam_Hightower
6       Addam Marbrand       /index.php/Addam_Marbrand
7         Addam Osgrey         /index.php/Addam_Osgrey
8         Addam Rivers         /index.php/Addam_Rivers
9       Addam Velaryon       /index.php/Addam_Velaryon

---
## Part 2 — Enrich each character page
For every character we scrape:
- **Infobox** → `father`, `mother`, `spouse`, `lover`, `issue`, `family`, `allegiance`
- **History / narrative sections** → `affiliated` (links that resolve to a known character ID)

In [5]:
import time
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed

# Load the character list we already scraped
df = pd.read_csv('characters.csv')

# Build a set of known character IDs for fast lookup (used to filter affiliated links)
known_ids = set(df['ID'].tolist())

BASE = 'https://awoiaf.westeros.org'

# Shared session with connection pooling — reuses TCP connections across threads
session = requests.Session()
session.headers.update({
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
})

INFOBOX_MAP = {
    'father':      'father',
    'mother':      'mother',
    'mothers':     'mother',
    'spouse':      'spouse',
    'spouses':     'spouse',
    'lover':       'lover',
    'lovers':      'lover',
    'consorts':    'lover',
    'issue':       'issue',
    'family':      'family',
    'allegiance':  'allegiance',
    'allegiances': 'allegiance',
}

SKIP_SECTIONS = {
    'references', 'notes', 'external links', 'see also',
    'quotes', 'behind the scenes', 'gallery',
}

def scrape_character(char_id):
    result = {col: '' for col in ['father', 'mother', 'spouse', 'lover', 'issue', 'family', 'allegiance', 'affiliated']}
    try:
        resp = session.get(BASE + char_id, timeout=15)
        if resp.status_code != 200:
            return char_id, result
        soup = BeautifulSoup(resp.content, 'html.parser')
    except Exception:
        return char_id, result

    # ── Infobox ──────────────────────────────────────────────────────────────
    infobox = soup.find('table', class_='infobox')
    if infobox:
        for row in infobox.find_all('tr'):
            th = row.find('th')
            td = row.find('td')
            if not (th and td):
                continue
            field = th.get_text(strip=True).lower()
            col = INFOBOX_MAP.get(field)
            if col is None:
                continue
            links = [a.get('href') for a in td.find_all('a') if a.get('href', '').startswith('/index.php/')]
            if links:
                result[col] = ';'.join(links)
            else:
                text = td.get_text(' ', strip=True)
                if text:
                    result[col] = text

    # ── Affiliated (narrative sections, filtered to known characters) ─────────
    content = soup.find('div', class_='mw-parser-output')
    if content:
        affiliated = []
        skip = False
        for elem in content.children:
            tag = getattr(elem, 'name', None)
            if tag == 'h2':
                skip = any(s in elem.get_text(strip=True).lower() for s in SKIP_SECTIONS)
            if skip:
                continue
            if tag in ('p', 'ul', 'ol', 'div', 'h3', 'h4'):
                for a in elem.find_all('a'):
                    href = a.get('href', '')
                    if href in known_ids and href not in affiliated:
                        affiliated.append(href)
        result['affiliated'] = ';'.join(affiliated)

    return char_id, result

print(f'Defined scraper. {len(df)} characters to enrich.')

Defined scraper. 3698 characters to enrich.

In [6]:
# 10 concurrent workers — ~10x faster than sequential
# Results come back out-of-order; we re-sort by the original index at the end

WORKERS = 10
CHECKPOINT_EVERY = 500

id_to_row = {row.ID: {'name': row.name, 'ID': row.ID} for row in df.itertuples()}
results = {}  # char_id -> result dict

futures = {}
with ThreadPoolExecutor(max_workers=WORKERS) as executor:
    for char_id in df['ID']:
        futures[executor.submit(scrape_character, char_id)] = char_id

    for i, future in enumerate(tqdm(as_completed(futures), total=len(futures), desc='Scraping')):
        char_id, data = future.result()
        results[char_id] = data

        if (i + 1) % CHECKPOINT_EVERY == 0:
            checkpoint_rows = [{**id_to_row[cid], **results[cid]} for cid in results]
            pd.DataFrame(checkpoint_rows).to_csv('characters_enriched.csv', index=False)

# Rebuild in original order
rows = [{**id_to_row[cid], **results[cid]} for cid in df['ID']]
enriched_df = pd.DataFrame(rows)
enriched_df.to_csv('characters_enriched.csv', index=False)
print(f'Done. {len(enriched_df)} rows, {len(enriched_df.columns)} columns.')
enriched_df.head(10)

Scraping:   0%|          | 0/3698 [00:00<?, ?it/s]

Scraping:   0%|          | 3/3698 [00:00<02:20, 26.30it/s]

Scraping:   0%|          | 12/3698 [00:00<01:08, 54.18it/s]

Scraping:   1%|          | 21/3698 [00:00<01:02, 58.73it/s]

Scraping:   1%|          | 27/3698 [00:00<01:40, 36.62it/s]

Scraping:   1%|          | 33/3698 [00:00<01:32, 39.81it/s]

Scraping:   1%|          | 40/3698 [00:00<01:32, 39.69it/s]

Scraping:   1%|          | 45/3698 [00:01<01:29, 40.65it/s]

Scraping:   1%|▏         | 50/3698 [00:01<01:36, 37.68it/s]

Scraping:   2%|▏         | 57/3698 [00:01<01:21, 44.45it/s]

Scraping:   2%|▏         | 63/3698 [00:01<01:20, 45.22it/s]

Scraping:   2%|▏         | 76/3698 [00:01<00:56, 64.04it/s]

Scraping:   2%|▏         | 86/3698 [00:01<00:50, 71.85it/s]

Scraping:   3%|▎         | 94/3698 [00:01<00:52, 68.95it/s]

Scraping:   3%|▎         | 107/3698 [00:01<00:45, 78.32it/s]

Scraping:   3%|▎         | 115/3698 [00:02<00:45, 78.60it/s]

Scraping:   3%|▎         | 127/3698 [00:02<00:41, 86.06it/s]

Scraping:   4%|▎         | 137/3698 [00:02<00:56, 63.32it/s]

Scraping:   4%|▍         | 148/3698 [00:02<00:49, 71.88it/s]

Scraping:   4%|▍         | 157/3698 [00:02<00:59, 59.42it/s]

Scraping:   4%|▍         | 164/3698 [00:02<01:08, 51.31it/s]

Scraping:   5%|▍         | 170/3698 [00:03<01:07, 52.37it/s]

Scraping:   5%|▍         | 177/3698 [00:03<01:16, 45.94it/s]

Scraping:   5%|▌         | 185/3698 [00:03<01:09, 50.47it/s]

Scraping:   5%|▌         | 194/3698 [00:03<01:00, 57.94it/s]

Scraping:   5%|▌         | 201/3698 [00:03<00:57, 60.42it/s]

Scraping:   6%|▌         | 210/3698 [00:03<00:52, 66.63it/s]

Scraping:   6%|▌         | 218/3698 [00:03<00:53, 65.16it/s]

Scraping:   6%|▌         | 226/3698 [00:03<00:52, 66.35it/s]

Scraping:   6%|▋         | 238/3698 [00:04<00:50, 67.89it/s]

Scraping:   7%|▋         | 247/3698 [00:04<00:47, 72.02it/s]

Scraping:   7%|▋         | 255/3698 [00:04<00:48, 70.75it/s]

Scraping:   7%|▋         | 263/3698 [00:04<00:54, 62.52it/s]

Scraping:   7%|▋         | 271/3698 [00:04<00:51, 65.93it/s]

Scraping:   8%|▊         | 278/3698 [00:04<00:58, 58.84it/s]

Scraping:   8%|▊         | 285/3698 [00:05<01:18, 43.28it/s]

Scraping:   8%|▊         | 291/3698 [00:05<01:27, 39.11it/s]

Scraping:   8%|▊         | 297/3698 [00:05<01:45, 32.37it/s]

Scraping:   8%|▊         | 306/3698 [00:05<01:22, 41.02it/s]

Scraping:   8%|▊         | 311/3698 [00:05<01:19, 42.36it/s]

Scraping:   9%|▊         | 322/3698 [00:05<00:59, 56.59it/s]

Scraping:   9%|▉         | 329/3698 [00:06<01:10, 47.53it/s]

Scraping:   9%|▉         | 335/3698 [00:06<01:09, 48.50it/s]

Scraping:   9%|▉         | 344/3698 [00:06<00:58, 57.36it/s]

Scraping:   9%|▉         | 351/3698 [00:06<01:25, 39.37it/s]

Scraping:  10%|▉         | 361/3698 [00:06<01:07, 49.78it/s]

Scraping:  10%|█         | 372/3698 [00:06<00:55, 60.25it/s]

Scraping:  10%|█         | 384/3698 [00:07<00:58, 56.54it/s]

Scraping:  11%|█         | 391/3698 [00:07<00:59, 55.80it/s]

Scraping:  11%|█         | 398/3698 [00:07<01:03, 51.77it/s]

Scraping:  11%|█         | 404/3698 [00:07<01:28, 37.40it/s]

Scraping:  11%|█         | 410/3698 [00:07<01:20, 40.76it/s]

Scraping:  11%|█▏        | 419/3698 [00:07<01:06, 49.17it/s]

Scraping:  12%|█▏        | 426/3698 [00:07<01:02, 52.20it/s]

Scraping:  12%|█▏        | 432/3698 [00:08<01:14, 43.83it/s]

Scraping:  12%|█▏        | 445/3698 [00:08<00:52, 61.73it/s]

Scraping:  12%|█▏        | 459/3698 [00:08<00:43, 75.10it/s]

Scraping:  13%|█▎        | 468/3698 [00:08<00:53, 60.30it/s]

Scraping:  13%|█▎        | 476/3698 [00:08<00:55, 58.25it/s]

Scraping:  13%|█▎        | 488/3698 [00:08<00:46, 68.72it/s]

Scraping:  13%|█▎        | 496/3698 [00:09<00:47, 67.44it/s]

Scraping:  14%|█▎        | 504/3698 [00:09<01:00, 53.12it/s]

Scraping:  14%|█▍        | 516/3698 [00:09<00:50, 62.71it/s]

Scraping:  14%|█▍        | 524/3698 [00:09<00:52, 59.94it/s]

Scraping:  14%|█▍        | 531/3698 [00:09<00:56, 56.53it/s]

Scraping:  15%|█▍        | 539/3698 [00:09<00:51, 61.49it/s]

Scraping:  15%|█▍        | 551/3698 [00:09<00:41, 74.96it/s]

Scraping:  15%|█▌        | 564/3698 [00:10<00:36, 84.88it/s]

Scraping:  16%|█▌        | 580/3698 [00:10<00:41, 75.16it/s]

Scraping:  16%|█▌        | 590/3698 [00:10<00:40, 76.60it/s]

Scraping:  16%|█▌        | 600/3698 [00:10<00:40, 76.24it/s]

Scraping:  16%|█▋        | 608/3698 [00:10<00:40, 75.43it/s]

Scraping:  17%|█▋        | 616/3698 [00:10<00:41, 74.79it/s]

Scraping:  17%|█▋        | 624/3698 [00:10<00:40, 75.76it/s]

Scraping:  17%|█▋        | 640/3698 [00:10<00:32, 93.48it/s]

Scraping:  18%|█▊        | 655/3698 [00:11<00:31, 96.46it/s]

Scraping:  18%|█▊        | 665/3698 [00:11<00:34, 87.67it/s]

Scraping:  18%|█▊        | 674/3698 [00:11<00:41, 72.93it/s]

Scraping:  19%|█▊        | 688/3698 [00:11<00:34, 87.10it/s]

Scraping:  19%|█▉        | 698/3698 [00:11<00:39, 76.68it/s]

Scraping:  19%|█▉        | 707/3698 [00:11<00:37, 78.89it/s]

Scraping:  19%|█▉        | 716/3698 [00:12<00:46, 64.69it/s]

Scraping:  20%|█▉        | 724/3698 [00:12<00:55, 53.33it/s]

Scraping:  20%|█▉        | 731/3698 [00:12<01:01, 48.09it/s]

Scraping:  20%|█▉        | 737/3698 [00:12<01:03, 46.64it/s]

Scraping:  20%|██        | 743/3698 [00:12<01:04, 45.91it/s]

Scraping:  20%|██        | 749/3698 [00:12<01:01, 47.95it/s]

Scraping:  21%|██        | 760/3698 [00:12<00:48, 60.39it/s]

Scraping:  21%|██        | 768/3698 [00:13<00:45, 63.80it/s]

Scraping:  21%|██        | 779/3698 [00:13<00:40, 72.55it/s]

Scraping:  21%|██▏       | 788/3698 [00:13<00:39, 73.80it/s]

Scraping:  22%|██▏       | 796/3698 [00:13<00:40, 71.92it/s]

Scraping:  22%|██▏       | 805/3698 [00:13<00:38, 74.48it/s]

Scraping:  22%|██▏       | 814/3698 [00:13<00:40, 70.53it/s]

Scraping:  22%|██▏       | 822/3698 [00:13<00:51, 56.14it/s]

Scraping:  22%|██▏       | 831/3698 [00:13<00:45, 62.37it/s]

Scraping:  23%|██▎       | 846/3698 [00:14<00:36, 77.46it/s]

Scraping:  23%|██▎       | 859/3698 [00:14<00:32, 86.84it/s]

Scraping:  23%|██▎       | 869/3698 [00:14<00:37, 75.52it/s]

Scraping:  24%|██▎       | 878/3698 [00:14<00:40, 69.95it/s]

Scraping:  24%|██▍       | 890/3698 [00:14<00:39, 71.23it/s]

Scraping:  25%|██▍       | 907/3698 [00:14<00:35, 79.17it/s]

Scraping:  25%|██▍       | 917/3698 [00:15<00:33, 82.85it/s]

Scraping:  25%|██▌       | 929/3698 [00:15<00:30, 90.25it/s]

Scraping:  25%|██▌       | 940/3698 [00:15<00:30, 91.60it/s]

Scraping:  26%|██▌       | 950/3698 [00:15<00:33, 82.87it/s]

Scraping:  26%|██▌       | 959/3698 [00:15<00:33, 81.48it/s]

Scraping:  26%|██▌       | 968/3698 [00:15<00:37, 72.61it/s]

Scraping:  26%|██▋       | 976/3698 [00:15<00:36, 73.83it/s]

Scraping:  27%|██▋       | 985/3698 [00:15<00:39, 68.27it/s]

Scraping:  27%|██▋       | 996/3698 [00:16<00:35, 75.29it/s]

Scraping:  27%|██▋       | 1004/3698 [00:16<00:46, 57.93it/s]

Scraping:  28%|██▊       | 1022/3698 [00:16<00:32, 83.07it/s]

Scraping:  28%|██▊       | 1032/3698 [00:16<00:32, 82.63it/s]

Scraping:  28%|██▊       | 1046/3698 [00:16<00:27, 96.13it/s]

Scraping:  29%|██▊       | 1060/3698 [00:16<00:25, 103.46it/s]

Scraping:  29%|██▉       | 1072/3698 [00:16<00:27, 96.62it/s]

Scraping:  29%|██▉       | 1083/3698 [00:17<00:30, 85.56it/s]

Scraping:  30%|██▉       | 1094/3698 [00:17<00:30, 86.11it/s]

Scraping:  30%|███       | 1110/3698 [00:17<00:25, 101.07it/s]

Scraping:  30%|███       | 1123/3698 [00:17<00:24, 103.90it/s]

Scraping:  31%|███       | 1134/3698 [00:17<00:30, 84.02it/s]

Scraping:  31%|███       | 1150/3698 [00:17<00:25, 100.69it/s]

Scraping:  32%|███▏      | 1165/3698 [00:17<00:25, 97.80it/s]

Scraping:  32%|███▏      | 1176/3698 [00:17<00:25, 98.04it/s]

Scraping:  32%|███▏      | 1187/3698 [00:18<00:29, 86.20it/s]

Scraping:  32%|███▏      | 1197/3698 [00:18<00:29, 85.71it/s]

Scraping:  33%|███▎      | 1211/3698 [00:18<00:28, 86.23it/s]

Scraping:  33%|███▎      | 1220/3698 [00:18<00:29, 84.46it/s]

Scraping:  33%|███▎      | 1231/3698 [00:18<00:27, 89.67it/s]

Scraping:  34%|███▎      | 1241/3698 [00:18<00:30, 80.61it/s]

Scraping:  34%|███▍      | 1252/3698 [00:18<00:28, 85.14it/s]

Scraping:  34%|███▍      | 1261/3698 [00:19<00:31, 78.59it/s]

Scraping:  34%|███▍      | 1270/3698 [00:19<00:31, 76.52it/s]

Scraping:  35%|███▍      | 1284/3698 [00:19<00:26, 90.47it/s]

Scraping:  35%|███▌      | 1297/3698 [00:19<00:24, 99.74it/s]

Scraping:  35%|███▌      | 1310/3698 [00:19<00:22, 105.89it/s]

Scraping:  36%|███▌      | 1321/3698 [00:19<00:26, 90.97it/s]

Scraping:  36%|███▌      | 1332/3698 [00:19<00:25, 93.80it/s]

Scraping:  37%|███▋      | 1350/3698 [00:19<00:20, 112.10it/s]

Scraping:  37%|███▋      | 1362/3698 [00:19<00:21, 110.73it/s]

Scraping:  37%|███▋      | 1376/3698 [00:20<00:20, 115.59it/s]

Scraping:  38%|███▊      | 1388/3698 [00:20<00:23, 96.33it/s]

Scraping:  38%|███▊      | 1403/3698 [00:20<00:21, 106.77it/s]

Scraping:  38%|███▊      | 1415/3698 [00:20<00:22, 101.60it/s]

Scraping:  39%|███▊      | 1432/3698 [00:20<00:22, 100.90it/s]

Scraping:  39%|███▉      | 1443/3698 [00:20<00:22, 98.98it/s]

Scraping:  39%|███▉      | 1454/3698 [00:20<00:23, 96.85it/s]

Scraping:  40%|███▉      | 1465/3698 [00:21<00:22, 100.09it/s]

Scraping:  40%|███▉      | 1476/3698 [00:21<00:23, 95.49it/s]

Scraping:  40%|████      | 1486/3698 [00:21<00:23, 94.31it/s]

Scraping:  41%|████      | 1500/3698 [00:21<00:20, 105.97it/s]

Scraping:  41%|████      | 1511/3698 [00:21<00:22, 96.19it/s]

Scraping:  41%|████      | 1523/3698 [00:21<00:22, 98.15it/s]

Scraping:  41%|████▏     | 1534/3698 [00:21<00:27, 79.25it/s]

Scraping:  42%|████▏     | 1544/3698 [00:21<00:28, 76.72it/s]

Scraping:  42%|████▏     | 1553/3698 [00:22<00:29, 71.62it/s]

Scraping:  42%|████▏     | 1565/3698 [00:22<00:27, 76.57it/s]

Scraping:  43%|████▎     | 1580/3698 [00:22<00:22, 93.00it/s]

Scraping:  43%|████▎     | 1590/3698 [00:22<00:22, 93.48it/s]

Scraping:  43%|████▎     | 1604/3698 [00:22<00:20, 100.01it/s]

Scraping:  44%|████▎     | 1615/3698 [00:22<00:22, 90.62it/s]

Scraping:  44%|████▍     | 1625/3698 [00:22<00:26, 79.60it/s]

Scraping:  44%|████▍     | 1634/3698 [00:23<00:30, 66.62it/s]

Scraping:  44%|████▍     | 1642/3698 [00:23<00:34, 59.28it/s]

Scraping:  45%|████▍     | 1650/3698 [00:23<00:33, 62.00it/s]

Scraping:  45%|████▍     | 1659/3698 [00:23<00:30, 65.88it/s]

Scraping:  45%|████▌     | 1674/3698 [00:23<00:24, 81.46it/s]

Scraping:  46%|████▌     | 1686/3698 [00:23<00:25, 77.87it/s]

Scraping:  46%|████▌     | 1695/3698 [00:23<00:25, 78.05it/s]

Scraping:  46%|████▌     | 1704/3698 [00:24<00:26, 76.36it/s]

Scraping:  46%|████▋     | 1713/3698 [00:24<00:25, 79.31it/s]

Scraping:  47%|████▋     | 1722/3698 [00:24<00:26, 74.96it/s]

Scraping:  47%|████▋     | 1730/3698 [00:24<00:26, 75.50it/s]

Scraping:  47%|████▋     | 1740/3698 [00:24<00:28, 68.61it/s]

Scraping:  47%|████▋     | 1752/3698 [00:24<00:24, 78.81it/s]

Scraping:  48%|████▊     | 1767/3698 [00:24<00:22, 87.21it/s]

Scraping:  48%|████▊     | 1776/3698 [00:24<00:24, 78.62it/s]

Scraping:  48%|████▊     | 1785/3698 [00:25<00:26, 72.46it/s]

Scraping:  48%|████▊     | 1793/3698 [00:25<00:25, 73.99it/s]

Scraping:  49%|████▉     | 1809/3698 [00:25<00:20, 92.95it/s]

Scraping:  49%|████▉     | 1819/3698 [00:25<00:24, 76.56it/s]

Scraping:  50%|████▉     | 1832/3698 [00:25<00:21, 87.47it/s]

Scraping:  50%|████▉     | 1843/3698 [00:25<00:21, 87.53it/s]

Scraping:  50%|█████     | 1857/3698 [00:25<00:18, 100.11it/s]

Scraping:  51%|█████     | 1868/3698 [00:26<00:20, 89.03it/s]

Scraping:  51%|█████     | 1881/3698 [00:26<00:18, 97.76it/s]

Scraping:  51%|█████     | 1892/3698 [00:26<00:21, 83.34it/s]

Scraping:  51%|█████▏    | 1903/3698 [00:26<00:20, 88.11it/s]

Scraping:  52%|█████▏    | 1913/3698 [00:26<00:21, 81.62it/s]

Scraping:  52%|█████▏    | 1922/3698 [00:26<00:23, 74.99it/s]

Scraping:  52%|█████▏    | 1933/3698 [00:26<00:21, 81.59it/s]

Scraping:  53%|█████▎    | 1942/3698 [00:26<00:25, 68.67it/s]

Scraping:  53%|█████▎    | 1959/3698 [00:27<00:19, 90.36it/s]

Scraping:  53%|█████▎    | 1970/3698 [00:27<00:22, 77.69it/s]

Scraping:  54%|█████▎    | 1983/3698 [00:27<00:19, 88.48it/s]

Scraping:  54%|█████▍    | 1993/3698 [00:27<00:19, 86.17it/s]

Scraping:  54%|█████▍    | 2003/3698 [00:27<00:26, 63.32it/s]

Scraping:  55%|█████▍    | 2021/3698 [00:27<00:20, 81.67it/s]

Scraping:  55%|█████▍    | 2031/3698 [00:28<00:21, 78.54it/s]

Scraping:  55%|█████▌    | 2042/3698 [00:28<00:20, 79.60it/s]

Scraping:  55%|█████▌    | 2051/3698 [00:28<00:24, 66.55it/s]

Scraping:  56%|█████▌    | 2059/3698 [00:28<00:25, 64.99it/s]

Scraping:  56%|█████▌    | 2069/3698 [00:28<00:22, 71.55it/s]

Scraping:  56%|█████▌    | 2077/3698 [00:28<00:23, 67.79it/s]

Scraping:  56%|█████▋    | 2087/3698 [00:28<00:21, 73.49it/s]

Scraping:  57%|█████▋    | 2095/3698 [00:29<00:25, 61.97it/s]

Scraping:  57%|█████▋    | 2102/3698 [00:29<00:31, 50.45it/s]

Scraping:  57%|█████▋    | 2111/3698 [00:29<00:28, 56.25it/s]

Scraping:  57%|█████▋    | 2118/3698 [00:29<00:26, 58.58it/s]

Scraping:  57%|█████▋    | 2126/3698 [00:29<00:24, 63.31it/s]

Scraping:  58%|█████▊    | 2134/3698 [00:29<00:23, 66.83it/s]

Scraping:  58%|█████▊    | 2147/3698 [00:29<00:19, 80.83it/s]

Scraping:  58%|█████▊    | 2156/3698 [00:29<00:20, 73.74it/s]

Scraping:  59%|█████▊    | 2164/3698 [00:30<00:23, 65.83it/s]

Scraping:  59%|█████▊    | 2171/3698 [00:30<00:25, 61.02it/s]

Scraping:  59%|█████▉    | 2178/3698 [00:30<00:24, 62.61it/s]

Scraping:  59%|█████▉    | 2187/3698 [00:30<00:21, 68.98it/s]

Scraping:  59%|█████▉    | 2195/3698 [00:30<00:21, 70.61it/s]

Scraping:  60%|█████▉    | 2203/3698 [00:30<00:23, 63.23it/s]

Scraping:  60%|█████▉    | 2215/3698 [00:30<00:19, 75.38it/s]

Scraping:  60%|██████    | 2232/3698 [00:30<00:14, 99.26it/s]

Scraping:  61%|██████    | 2243/3698 [00:31<00:18, 80.22it/s]

Scraping:  61%|██████    | 2252/3698 [00:31<00:18, 80.33it/s]

Scraping:  61%|██████    | 2261/3698 [00:31<00:19, 73.35it/s]

Scraping:  62%|██████▏   | 2275/3698 [00:31<00:16, 87.94it/s]

Scraping:  62%|██████▏   | 2285/3698 [00:31<00:16, 84.31it/s]

Scraping:  62%|██████▏   | 2298/3698 [00:31<00:16, 87.13it/s]

Scraping:  62%|██████▏   | 2309/3698 [00:31<00:16, 83.64it/s]

Scraping:  63%|██████▎   | 2323/3698 [00:32<00:14, 91.74it/s]

Scraping:  63%|██████▎   | 2335/3698 [00:32<00:14, 96.20it/s]

Scraping:  63%|██████▎   | 2348/3698 [00:32<00:12, 104.29it/s]

Scraping:  64%|██████▍   | 2363/3698 [00:32<00:11, 115.96it/s]

Scraping:  64%|██████▍   | 2375/3698 [00:32<00:13, 101.63it/s]

Scraping:  65%|██████▍   | 2388/3698 [00:32<00:13, 97.46it/s]

Scraping:  65%|██████▍   | 2399/3698 [00:32<00:13, 99.53it/s]

Scraping:  65%|██████▌   | 2410/3698 [00:33<00:17, 75.68it/s]

Scraping:  65%|██████▌   | 2419/3698 [00:33<00:16, 76.35it/s]

Scraping:  66%|██████▌   | 2428/3698 [00:33<00:17, 72.00it/s]

Scraping:  66%|██████▌   | 2444/3698 [00:33<00:13, 92.06it/s]

Scraping:  66%|██████▋   | 2455/3698 [00:33<00:14, 85.03it/s]

Scraping:  67%|██████▋   | 2467/3698 [00:33<00:13, 92.83it/s]

Scraping:  67%|██████▋   | 2478/3698 [00:33<00:15, 77.68it/s]

Scraping:  67%|██████▋   | 2491/3698 [00:33<00:13, 88.79it/s]

Scraping:  68%|██████▊   | 2501/3698 [00:34<00:20, 58.63it/s]

Scraping:  68%|██████▊   | 2522/3698 [00:34<00:13, 84.40it/s]

Scraping:  69%|██████▊   | 2534/3698 [00:34<00:13, 83.62it/s]

Scraping:  69%|██████▉   | 2545/3698 [00:34<00:13, 83.45it/s]

Scraping:  69%|██████▉   | 2555/3698 [00:34<00:16, 70.41it/s]

Scraping:  69%|██████▉   | 2564/3698 [00:35<00:16, 67.95it/s]

Scraping:  70%|██████▉   | 2573/3698 [00:35<00:15, 72.02it/s]

Scraping:  70%|██████▉   | 2582/3698 [00:35<00:16, 66.41it/s]

Scraping:  70%|███████   | 2590/3698 [00:35<00:16, 67.15it/s]

Scraping:  70%|███████   | 2598/3698 [00:35<00:15, 69.41it/s]

Scraping:  70%|███████   | 2606/3698 [00:35<00:17, 63.44it/s]

Scraping:  71%|███████   | 2619/3698 [00:35<00:13, 77.64it/s]

Scraping:  71%|███████   | 2628/3698 [00:35<00:14, 72.59it/s]

Scraping:  71%|███████▏  | 2636/3698 [00:36<00:14, 71.42it/s]

Scraping:  72%|███████▏  | 2647/3698 [00:36<00:13, 79.63it/s]

Scraping:  72%|███████▏  | 2656/3698 [00:36<00:13, 77.49it/s]

Scraping:  72%|███████▏  | 2664/3698 [00:36<00:15, 67.07it/s]

Scraping:  72%|███████▏  | 2672/3698 [00:36<00:14, 68.94it/s]

Scraping:  72%|███████▏  | 2681/3698 [00:36<00:13, 74.22it/s]

Scraping:  73%|███████▎  | 2689/3698 [00:36<00:14, 71.79it/s]

Scraping:  73%|███████▎  | 2697/3698 [00:36<00:16, 62.11it/s]

Scraping:  73%|███████▎  | 2710/3698 [00:37<00:13, 73.63it/s]

Scraping:  73%|███████▎  | 2718/3698 [00:37<00:13, 71.21it/s]

Scraping:  74%|███████▎  | 2726/3698 [00:37<00:14, 67.18it/s]

Scraping:  74%|███████▍  | 2735/3698 [00:37<00:14, 67.80it/s]

Scraping:  74%|███████▍  | 2742/3698 [00:37<00:13, 68.31it/s]

Scraping:  74%|███████▍  | 2749/3698 [00:37<00:14, 66.33it/s]

Scraping:  75%|███████▍  | 2757/3698 [00:37<00:14, 67.02it/s]

Scraping:  75%|███████▍  | 2768/3698 [00:37<00:15, 61.71it/s]

Scraping:  75%|███████▌  | 2777/3698 [00:38<00:14, 61.91it/s]

Scraping:  75%|███████▌  | 2784/3698 [00:38<00:16, 54.71it/s]

Scraping:  75%|███████▌  | 2790/3698 [00:38<00:20, 44.86it/s]

Scraping:  76%|███████▌  | 2795/3698 [00:38<00:20, 43.24it/s]

Scraping:  76%|███████▌  | 2807/3698 [00:38<00:15, 57.83it/s]

Scraping:  76%|███████▌  | 2814/3698 [00:38<00:16, 52.62it/s]

Scraping:  76%|███████▋  | 2820/3698 [00:39<00:17, 50.41it/s]

Scraping:  76%|███████▋  | 2826/3698 [00:39<00:18, 48.05it/s]

Scraping:  77%|███████▋  | 2831/3698 [00:39<00:18, 46.57it/s]

Scraping:  77%|███████▋  | 2844/3698 [00:39<00:14, 60.70it/s]

Scraping:  77%|███████▋  | 2851/3698 [00:39<00:15, 55.29it/s]

Scraping:  77%|███████▋  | 2864/3698 [00:39<00:11, 71.77it/s]

Scraping:  78%|███████▊  | 2872/3698 [00:39<00:12, 67.04it/s]

Scraping:  78%|███████▊  | 2882/3698 [00:39<00:11, 69.96it/s]

Scraping:  78%|███████▊  | 2890/3698 [00:40<00:12, 63.33it/s]

Scraping:  78%|███████▊  | 2899/3698 [00:40<00:11, 67.87it/s]

Scraping:  79%|███████▊  | 2907/3698 [00:40<00:11, 66.66it/s]

Scraping:  79%|███████▉  | 2916/3698 [00:40<00:14, 55.50it/s]

Scraping:  79%|███████▉  | 2926/3698 [00:40<00:12, 60.46it/s]

Scraping:  79%|███████▉  | 2934/3698 [00:40<00:12, 62.30it/s]

Scraping:  80%|███████▉  | 2949/3698 [00:40<00:09, 80.70it/s]

Scraping:  80%|███████▉  | 2958/3698 [00:41<00:10, 70.97it/s]

Scraping:  80%|████████  | 2966/3698 [00:41<00:10, 68.31it/s]

Scraping:  80%|████████  | 2974/3698 [00:41<00:11, 65.39it/s]

Scraping:  81%|████████  | 2984/3698 [00:41<00:10, 70.45it/s]

Scraping:  81%|████████  | 2992/3698 [00:41<00:11, 62.35it/s]

Scraping:  81%|████████  | 2999/3698 [00:41<00:11, 59.79it/s]

Scraping:  81%|████████▏ | 3008/3698 [00:41<00:10, 66.40it/s]

Scraping:  82%|████████▏ | 3018/3698 [00:42<00:09, 73.30it/s]

Scraping:  82%|████████▏ | 3026/3698 [00:42<00:10, 65.73it/s]

Scraping:  82%|████████▏ | 3033/3698 [00:42<00:10, 62.71it/s]

Scraping:  82%|████████▏ | 3040/3698 [00:42<00:12, 51.02it/s]

Scraping:  82%|████████▏ | 3049/3698 [00:42<00:12, 51.69it/s]

Scraping:  83%|████████▎ | 3058/3698 [00:42<00:10, 59.18it/s]

Scraping:  83%|████████▎ | 3065/3698 [00:42<00:11, 55.06it/s]

Scraping:  83%|████████▎ | 3074/3698 [00:43<00:10, 61.95it/s]

Scraping:  83%|████████▎ | 3084/3698 [00:43<00:09, 64.67it/s]

Scraping:  84%|████████▎ | 3095/3698 [00:43<00:08, 75.21it/s]

Scraping:  84%|████████▍ | 3103/3698 [00:43<00:07, 74.77it/s]

Scraping:  84%|████████▍ | 3111/3698 [00:43<00:07, 75.74it/s]

Scraping:  84%|████████▍ | 3124/3698 [00:43<00:06, 90.11it/s]

Scraping:  85%|████████▍ | 3134/3698 [00:43<00:07, 78.47it/s]

Scraping:  85%|████████▍ | 3143/3698 [00:43<00:07, 69.66it/s]

Scraping:  85%|████████▌ | 3153/3698 [00:44<00:07, 71.06it/s]

Scraping:  86%|████████▌ | 3164/3698 [00:44<00:06, 79.38it/s]

Scraping:  86%|████████▌ | 3173/3698 [00:44<00:08, 63.64it/s]

Scraping:  86%|████████▌ | 3181/3698 [00:44<00:07, 65.66it/s]

Scraping:  86%|████████▋ | 3192/3698 [00:44<00:06, 72.56it/s]

Scraping:  87%|████████▋ | 3200/3698 [00:44<00:07, 62.87it/s]

Scraping:  87%|████████▋ | 3210/3698 [00:44<00:07, 67.08it/s]

Scraping:  87%|████████▋ | 3218/3698 [00:45<00:07, 63.97it/s]

Scraping:  87%|████████▋ | 3231/3698 [00:45<00:05, 78.75it/s]

Scraping:  88%|████████▊ | 3240/3698 [00:45<00:06, 67.60it/s]

Scraping:  88%|████████▊ | 3248/3698 [00:45<00:06, 68.58it/s]

Scraping:  88%|████████▊ | 3256/3698 [00:45<00:06, 64.25it/s]

Scraping:  88%|████████▊ | 3265/3698 [00:45<00:06, 70.03it/s]

Scraping:  89%|████████▊ | 3273/3698 [00:45<00:06, 64.52it/s]

Scraping:  89%|████████▉ | 3283/3698 [00:46<00:06, 62.89it/s]

Scraping:  89%|████████▉ | 3295/3698 [00:46<00:06, 65.17it/s]

Scraping:  89%|████████▉ | 3306/3698 [00:46<00:05, 66.19it/s]

Scraping:  90%|████████▉ | 3315/3698 [00:46<00:05, 70.51it/s]

Scraping:  90%|████████▉ | 3323/3698 [00:46<00:05, 71.52it/s]

Scraping:  90%|█████████ | 3335/3698 [00:46<00:04, 82.40it/s]

Scraping:  90%|█████████ | 3344/3698 [00:46<00:05, 66.16it/s]

Scraping:  91%|█████████ | 3352/3698 [00:47<00:05, 66.84it/s]

Scraping:  91%|█████████ | 3361/3698 [00:47<00:04, 71.20it/s]

Scraping:  91%|█████████ | 3370/3698 [00:47<00:04, 72.19it/s]

Scraping:  91%|█████████▏| 3380/3698 [00:47<00:05, 59.21it/s]

Scraping:  92%|█████████▏| 3387/3698 [00:47<00:05, 59.05it/s]

Scraping:  92%|█████████▏| 3395/3698 [00:47<00:04, 62.77it/s]

Scraping:  92%|█████████▏| 3402/3698 [00:47<00:05, 57.02it/s]

Scraping:  92%|█████████▏| 3409/3698 [00:47<00:05, 57.09it/s]

Scraping:  92%|█████████▏| 3415/3698 [00:48<00:06, 47.04it/s]

Scraping:  93%|█████████▎| 3426/3698 [00:48<00:04, 59.29it/s]

Scraping:  93%|█████████▎| 3436/3698 [00:48<00:04, 57.56it/s]

Scraping:  93%|█████████▎| 3443/3698 [00:48<00:04, 54.18it/s]

Scraping:  93%|█████████▎| 3455/3698 [00:48<00:03, 65.58it/s]

Scraping:  94%|█████████▎| 3465/3698 [00:48<00:03, 73.33it/s]

Scraping:  94%|█████████▍| 3473/3698 [00:48<00:03, 67.81it/s]

Scraping:  94%|█████████▍| 3481/3698 [00:49<00:03, 60.68it/s]

Scraping:  94%|█████████▍| 3490/3698 [00:49<00:03, 66.99it/s]

Scraping:  95%|█████████▍| 3498/3698 [00:49<00:03, 52.40it/s]

Scraping:  95%|█████████▍| 3508/3698 [00:49<00:03, 59.10it/s]

Scraping:  95%|█████████▌| 3515/3698 [00:49<00:03, 53.56it/s]

Scraping:  95%|█████████▌| 3524/3698 [00:49<00:02, 59.09it/s]

Scraping:  95%|█████████▌| 3531/3698 [00:50<00:03, 50.47it/s]

Scraping:  96%|█████████▌| 3542/3698 [00:50<00:02, 62.94it/s]

Scraping:  96%|█████████▌| 3550/3698 [00:50<00:02, 60.26it/s]

Scraping:  96%|█████████▌| 3558/3698 [00:50<00:02, 64.23it/s]

Scraping:  96%|█████████▋| 3565/3698 [00:50<00:02, 60.51it/s]

Scraping:  97%|█████████▋| 3575/3698 [00:50<00:01, 67.85it/s]

Scraping:  97%|█████████▋| 3586/3698 [00:50<00:01, 76.82it/s]

Scraping:  97%|█████████▋| 3595/3698 [00:50<00:01, 67.46it/s]

Scraping:  97%|█████████▋| 3603/3698 [00:51<00:01, 56.41it/s]

Scraping:  98%|█████████▊| 3614/3698 [00:51<00:01, 63.92it/s]

Scraping:  98%|█████████▊| 3621/3698 [00:51<00:01, 63.71it/s]

Scraping:  98%|█████████▊| 3628/3698 [00:51<00:01, 53.10it/s]

Scraping:  98%|█████████▊| 3641/3698 [00:51<00:00, 69.54it/s]

Scraping:  99%|█████████▊| 3649/3698 [00:51<00:00, 66.15it/s]

Scraping:  99%|█████████▉| 3660/3698 [00:51<00:00, 74.21it/s]

Scraping:  99%|█████████▉| 3669/3698 [00:52<00:00, 63.97it/s]

Scraping:  99%|█████████▉| 3678/3698 [00:52<00:00, 60.97it/s]

Scraping: 100%|█████████▉| 3689/3698 [00:52<00:00, 70.14it/s]

Scraping: 100%|██████████| 3698/3698 [00:52<00:00, 56.67it/s]

Scraping: 100%|██████████| 3698/3698 [00:52<00:00, 70.21it/s]

Done. 3698 rows, 10 columns.

,name,ID,father,mother,spouse,lover,issue,family,allegiance,affiliated
0,A certain man,/index.php/A_certain_man,,,,,,,,/index.php/Varys;/index.php/Tyrion_Lannister;/...
1,Abelar Hightower,/index.php/Abelar_Hightower,,,,,,,/index.php/House_Hightower,/index.php/Daeron_II_Targaryen;/index.php/Dunc...
2,Abelon,/index.php/Abelon,,,,,,,/index.php/Citadel,
3,Addam of Duskendale,/index.php/Addam_of_Duskendale,,,,,,,,
4,Addam Frey,/index.php/Addam_Frey,,,,,,,/index.php/House_Frey,/index.php/Aerys_I_Targaryen;/index.php/Lord_F...
5,Addam Hightower,/index.php/Addam_Hightower,/index.php/Manfred_Hightower_(Aegon%27s_Conquest),,Unknown,,/index.php/Manfred_Hightower_(son_of_Addam);/i...,,/index.php/House_Hightower;/index.php/House_Ty...,/index.php/Aegon_I_Targaryen;/index.php/Garmon...
6,Addam Marbrand,/index.php/Addam_Marbrand,/index.php/Damon_Marbrand,,,,,,/index.php/House_Marbrand;/index.php/House_Lan...,/index.php/Damon_Marbrand;/index.php/Tywin_Lan...
7,Addam Osgrey,/index.php/Addam_Osgrey,/index.php/Eustace_Osgrey,,,,,,/index.php/House_Osgrey,/index.php/Daeron_II_Targaryen;/index.php/Eust...
8,Addam Rivers,/index.php/Addam_Rivers,,,,,,,,/index.php/Arlan_III_Durrandon
9,Addam Velaryon,/index.php/Addam_Velaryon,,/index.php/Marilda_of_Hull,,,,,/index.php/House_Velaryon;/index.php/House_Tar...,/index.php/Alyn_Velaryon;/index.php/Marilda_of...